mggg/GerryChain

- docs/conf.py
- docs/index.rst
- docs/models.rst
- docs/modules.rst
- docs/rundmcmc.rst
- docs/setup.rst
- docs/tests.rst
These commits get the sphinx docs in a more functional state with autodoc. Most importantly, the `.rst` files were autogenerated with `sphinx-apidoc`.
> Setup autodocs with sphinx-apidoc

- rundmcmc/ingest.py
Previously, ingest was unnecessarily unpacking the pysal weights into an adjacency matrix, but it is conveniently already provided in a dictionary. So I streamlined it.
More importantly, the previous version was not actually computing the shared perimeters between neighbors, but just listing the full perimeter of each shape.
I’ve made it so the output is identical to before (with the corrected shared perimeter values), but I think that the sorting is unnecessary and that the plain neighbors and shared_perims dicts could be handed off to the networkx generation function in their original form, and that integer IDs could be assigned there. Probably doesn’t matter much, but you could potentially have an indexing headache somewhere.
> Compute shared perimeters, streamline ingestion

- docs/conf.py
RTD can't handle arbitrary C libraries. This mocks the those so that RTD can import our files and correctly autobuild docs.
> Fix C dependency issues with RTD

- rundmcmc/updaters.py
- tests/test_updaters.py
- `cut_edges_by_part` returns a dictionary from districts to the set of edges from that district to other districts. This will be helpful in implementing perimeter updaters and Polsby-Popper. Closes #74 .
- Fixed some bugs in the existing cut_edges. Basically, any time we manipulate sets of edges we need to use `tuple(sorted(edge))` instead of `edge`, to make sure we don't accidentally have two copies of the same edge (with just different orders of nodes) in the set. Would it be worth it to implement an edge set class that does this for you?
> Fixed some bugs, and implemented cut_edges_by_part

- rundmcmc/__init__.py
- rundmcmc/__main__.py
* Can run chain outside of rundmcmc folder
* Can output directly into the folder you want
* Don't need to call `__main__` directly. Instead `rundmcmc config.ini`
> run chain with rundmcmc config.ini

- rundmcmc/output.py
P-value reports were counting all the plans that were strictly worse in the initial plan. This isn't what you want, because if your initial plan is the worst you see, you end up with a p-value of 0, which looks silly.
> Change > to >=

- README.rst
We've had some complaints about the RTD badge being too easy to miss. You can't miss big, bold links!
> Add big, bold links to docs in README

- rundmcmc/generate_config.py
- rundmcmc/validity.py
Now the constraint is called 'no_worse_L1_polsby_popper'.
I also added the L^{-1} polsby popper score/constraint.
> Fixed L1 polsby popper bug, add L^{-1}

- rundmcmc/vis_output.py
Previously running a single histogram would crash the output. Now automatically flattens the subplot list if there is a single column so that quadrant works and has squeeze=False so that we still get a 2d array if there are two plots. 
Also added some spacing so the titles don't collide with the x labels.
> 1, 2, and 3+ histogram subplots now work

- rundmcmc/generate_config.py
- rundmcmc/parse_config.py
- rundmcmc/validity.py
new class in validity.py allows one to specify a validator and allow a percentage of the 
original plan's range tolerance. TODO: insure that this spits out rage if someone tries to use it with boolean-valued validity functions
> Added tolerance for validity functions based on original districting plan

- rundmcmc/parse_config.py
This lets graphs be saved once created from config files. Usage is simple: add a `save_json` path field to the `GRAPH_SOURCE` section. If the file exists, then it's loaded as a networkx JSON object. If it doesn't, then the graph is created as usual, then saved there.
This also fixes the issue described in #161.
> Add a graph save feature to the config parser

- rundmcmc/updaters/tally.py
This adds a quick check if the data being added up in `Tally` is a nan. If it is, it is loudly discarded so that users know there is an issue with their data. I think that ignoring nan's is the most common use case, so this should be uncontroversial.
> Add nan check to Tally

- rundmcmc/parse_config.py
- rundmcmc/scores.py
- rundmcmc/template_main.py
- rundmcmc/template_main_multi.py
- rundmcmc/vis_output.py
Two big things here:
1. Adjusted the chain config to use votes_updaters in order to compute correct mean medians. This means that currently you can only use a single election at once through the GUI and you must use both columns, even if you are just computing mean median.
2. The new template_main_multi.py is the current state of the art for running chains. It has a bunch of nice new features:
a) creates new folder for output
b) allows you to run multiple sets of voting data through the partisan metrics on a single run
c) cleans up the histogram output with spacing and titles for plots
> Fixed Mean-Median config error + Multi_votes

- rundmcmc/parse_log.py
- rundmcmc/template_main_multi.py
- rundmcmc/validity.py
This adds a simple logging feature to `template_main_multi.py` that will track how often certain validators are rejecting proposals. Also, `Bound`, `UpperBound`, and `LowerBound` now have meaningful `__name__` attributes.
> Add validator tracking to template

- examples/parts_graph.py
- rundmcmc/make_graph.py
- tests/test_make_graph.py
- Avoid itertuples to allow for column names that start with numbers. This closes #177 . Also added a test to prove that this works.
- Added an example of getting the parts-level adjacency matrix, for the Alaska team.
- Moved some parts of `construct_graph_from_df` into their own functions, for clarity.
> Allow column names that start with numbers

- rundmcmc/grid.py
- rundmcmc/run.py
- rundmcmc/scores.py
- rundmcmc/template_main_grid.py
- rundmcmc/template_main_multi.py
Modified template to report chain stats separately from partisan metrics. This requires adding a couple of silly functions to scores in order to call with the proper syntax. 
Moved output writing to a new Outputs folder. 
Updated the terminology for number_to_display and number_to_bin. 
Also included a grid example for testing proposals and acceptance functions.
> Building out template functionality and grid example

- rundmcmc/make_graph.py
- rundmcmc/scores.py
- tests/test_make_graph.py
- tests/test_scores.py
I added `id_column` back in as an optional argument.
If it is provided then `add_data_to_graph` makes a view of the dataframe indexed by `id_column` and then adds the data. If it is not provided, it assumes that the dataframe is already indexed by node id. This avoids setting the index on the dataframe permanently.
One point of concern is whether people might forget to include the id_column argument, leading to the data not being added, or being added incorrectly. But I think this usage would raise a KeyError when networkx tries to find a node using the wrong ids. One scary scenario where it wouldn't raise a KeyError is if you indexed your nodes by row number, and now are trying to add data from a CSV, also indexed by row number, but where the rows do not match up properly. That situation …
> Accept id_column argument in add_data_to_graph

- rundmcmc/validity/__init__.py
One of the functions got left out of the __init__
> Missing no more disconnected from init

- rundmcmc/validity/validity.py
`single_flip_contiguity()` is now significantly faster. It uses a modified Dijkstra's algorithm hoisted from NetworkX's implementation that (1) avoids specified nodes, and (2) halts when a specified set of nodes are found.
This is still peanuts in terms of total performance, but it shaves a little off the top.
> Contiguity check speedup

- rundmcmc/updaters/flows.py
This makes the flow computations in flows.py faster by removing an unnecessary dict merge and avoiding looping through parts without flows (which would be almost all the parts).
I profiled this by running test_defaults, but with 10,000 steps instead of 100. It went from taking 45 seconds to 35 seconds, which is kind of crazy. We'll see how much it helps for other configurations.
> Avoid looping through empty flows, remove unnecessary dict merge

- README.rst
The link that was there was broken, so I found the link I think it's supposed to point to.
> Change link to getting started guide

- docs/user/quickstart.rst
- gerrychain/graph/adjacency.py
- gerrychain/graph/graph.py
- gerrychain/partition/partition.py
- tests/test_make_graph.py
Some assumptions I was making in writing the Getting started guide were not backed up by the actual `Graph` implementation. Yikes! This pull request will fix those discrepancies, both by changing implementation and by improving documentation.
I also decided to use a dictionary comprehension instead of the `networkx.get_node_attributes` method, because NetworkX method doesn't care if values are missing (and silences errors!).
> Bring `Graph` in line with Getting started guide; Add test for `from_file()`

- gerrychain/partition/partition.py
- tests/test_make_graph.py
- tests/test_updaters.py
- Don't update all the updaters at every step of the chain, just the ones that are requested. The test suite passes without doing it, and could help performance in situations with many invalid proposals and lots of updaters. This closes #218 .
- Add test that a GeoDataFrame with a missing CRS raises an error when creating a graph. This happens in geopandas, but we want to make sure it happens.
- Add test that election result vote counts are correct through the lifetime of a short chain. This is a test that wrapping the Tally updaters in the Election updater isn't throwing off the way we use the parent partition's values to get new values.
- Small change: check that `parent is None` instead of casting `parent` to a boolean. Just reduces the slightest bit of overhead.
> Lazily update

- gerrychain/scores.py
- tests/test_scores.py
This PR implements issue #241. It adds two new scores to `gerrychain.scores`:
- **Partisan bias.** The scoring function implements @mduchin's definition ("the number of districts with above-mean Republican share divided by the total number of districts, minus 1/2") but uses the first party of the given `ElectionResults` object rather than hardcoding the GOP. This follows the convention used by the other scoring functions.
- **Partisan Gini.** This score is rather esoteric—there seems to be little definitional information available other than #241. I referred to [these Tufts Math 19 lecture notes (pdf)](https://sites.tufts.edu/socialchoice/files/2018/01/partisan.pdf), which explain how to generate a seats-votes curve from a single election under the assumption of uniform partisan swing. …
> Partisan bias and partisan Gini scores

- gerrychain/partition/partition.py
Migrating discussion of Issue #280 (making sure assignments have nodes named in the same way as the graph).
Points to discuss: 
- Is the initialization of the `Partition` object the right place to do this check?
- Should the `Assignment` class implement the `collections.Mapping` stuff?
- Is `NameError` the right exception? `KeyError`? `ValueError`?
> first implementation of validating node names

- gerrychain/partition/partition.py
- tests/partition/test_partition.py
The stuff I wrote yesterday doesn't handle the case where all of the unit names are correct, but the assignment has some unit in more than one district. This checks for that problem as well.
> Missed case in assignment checking

- MANIFEST.in
- gerrychain/tree.py
Two main changes:
- When we recursively contract leaves of the tree, the leaves at step `n` must be a subset of the predecessors of the leaves at step `n-1`. So instead of scanning all the nodes to find the leaves at each step, we store the leaves in a `deque`, and add the predecessors to the back of the deque if their degree is 1 after contracting the nodes.
- Keep track of the degrees of the nodes in a dictionary, and update those values instead of actually calling `networkx.Graph.remove_node()`. This leaves the spanning tree graph intact, so we don't have to make a new copy every time we retry.
This seemed to speed things up a bit! I profiled the old version and this version splitting Chicago's precinct graph in half, and `contract_leaves_until_balanced_or_none` went from being by far …
> Some ReCom optimizations.

- docs/api.rst
- gerrychain/constraints/__init__.py
- gerrychain/graph/graph.py
- gerrychain/partition/partition.py
- gerrychain/proposals/__init__.py
- Add `__all__` to `gerrychain.proposals`, ensuring that autodoc actually does what it should.
- Modify "Binary constraints" section to link to relevant classes and methods.
> Fix autodoc and links

- gerrychain/constraints/validity.py
- tests/constraints/test_validity.py
I've run into the following error several times over the past few weeks when trying to run a chain with the `within_percent_of_ideal_population` constraint, which returns a `Bounds` object:
```
Traceback (most recent call last):
File "minimal_example.py", line 44, in <module>
total_steps=100
File "<...>/GerryChain/gerrychain/chain.py", line 37, in __init__
if not is_valid(initial_state):
File "<...>/GerryChain/gerrychain/constraints/validity.py", line 44, in __call__
"Constraint {} returned a non-boolean.".format(repr(constraint))
TypeError: Constraint <gerrychain.constraints.bounds.Bounds object at 0x115c94358> returned a non-boolean.
```
This error seems to occur when the population bounds stored in the `Bounds` object are NumPy floats rather than native Python floats. This causes …
> Allow NumPy booleans as constraint return values

- gerrychain/partition/partition.py
- tests/partition/test_partition.py
Adds the `cut_edges` updater to the `Partition` class by default. In addition to this being an ease-of-use feature, it fixes #314. Furthermore, this allows for us to easily add default updaters in the future.
> Built-in updaters

- docs/user/partitions.md
- docs/user/quickstart.rst
- docs/user/recom.rst
Updates at MGGG-states caused the original quickstart doc code to fail. This replaces that shapefile with a json throughout for maintainability purposes.
> update docs to use json - fixes errors

- gerrychain/updaters/locality_split_scores.py
- tests/partition/test_partition.py
- tests/test_make_graph.py
Addressed issues related to the 3 failing and 1 error when running unit tests.
The first major group of errors had to do with accessing the deprecated `node` property, which is now `nodes`.  The second error related to a unit test attempting to delete the `crs` property of a `geodataframe` object. This was solved by setting the property to `None` which should simulate the same failure behavior. 
Please let me know if you have any questions or recommendations on modifications to this PR.
> Fix errors in unit tests

- gerrychain/tree.py
There is an an unknown `KeyError` bug that appears from the contraction function. The current fix is to change the default to be the memoization method of finding balanced cut edges in a spanning tree.
This isn't necessarily a hotfix, because the intention was to move to this memoization function anyway because of its faster performance. However, this bug did urge this merge in earlier than I intended it to.
Opened that bug as #352
> Fix key error on contraction

- gerrychain/__init__.py
This PR is a stopgap measure to disable PyGeos by default. This addresses https://github.com/geopandas/geopandas/issues/2199 while we wait for a response/upstream fix.
> Polygon id fix/mitigation

- gerrychain/partition/assignment.py
This PR improves scoring/partition creating/replaying speeds by 2-3x (tested on PA congressional and MI state house ensembles). The performance issue I discovered is that because `cut_edges` is a default, forced updater for every partition class (there is actually no way to opt-out of this!), this function https://github.com/mggg/GerryChain/blob/198f43dae397a7e361dcaa059a7ac8a4e0ff18f3/gerrychain/updaters/flows.py#L65 is called on each flip/partition creation. This function creates a lot of `Assignment.__getitem__` calls, which opens up an area for speedups.
`Assignment.__getitem__` is called many, many times and is the most frequently called method/attribute when replaying a chain (according to cProfile). For example, on a replay of PA, it is called over `15376706` times. For context, …
> Track node to part mapping in Assignment to reduce overhead of expensive __getitem__ calls

- .circleci/config.yml
- setup.py
Some of the latest releases of our upstream dependencies no longer support Python 3.7 (apparently, from a cursory glance at our CircleCI logs). This fixes CI so we can get on with GerryChain development and merge in #363.
Some other notes:
- I can confirm that Python 3.7 still works on my computer with some manual dependency wrangling (a simple `python setup.py install` won't work). 
- Python 3.6 is end-of-life, so I think we should remove it from the list of officially supported Python versions
> Bump CircleCI Python version to 3.8

- gerrychain/partition/partition.py
- tests/constraints/test_validity.py
_(I'm not sure if this is worth it yet, but figured I'd throw up a PR and we can do some benchmarks.)_ I was just reminded that using `__slots__` is known to improve memory usage (and sometimes performance) of Python classes [(see here)](https://book.pythontips.com/en/latest/__slots__magic.html), at least when the classes are small. I suspect our memory usage is dominated by large assignment dictionaries, but maybe this is a step in the right direction. `__slots__` also protects against abuse of the `Partition` class by preventing the use of additional fields, though this may break some people's code.
> Use __slots__ in Partition

- .circleci/config.yml
- tests/conftest.py
- tests/test_reproducibility.py
Some time ago, I flagged a few historical commits that unintentionally produce different chain outputs (with the same seed, etc). This is concerning (since it could mean that correctness issues were introduced in those commits). This PR adds a "seed and freeze" test to loudly detect such changes.
> Add seed and freeze test to loudly detect when breaking changes are made

- gerrychain/updaters/cut_edges.py
- gerrychain/updaters/flows.py
This is a PR broken out from #372 to ease the code review process.
In particular, this patch is intended to improve the performance of calculating `cut_edges` by introducing a `neighbor_flips` function to cache the set of neighbors of all flipped nodes. This is used to calculate the cut edges of a plan as the set of all flipped nodes is a superset of the cut edges. 
Since this is looped over a few times throughout the lifetime of a Partition object, caching improves replay performance considerably.
> Add neighborhood flips caching

- gerrychain/partition/assignment.py
- gerrychain/partition/subgraphs.py
This is a PR broken out from #372 to ease the code review process.
In particular, this patch adds the `__slots__` method to a few classes that are created often, which improves memory and runtime performance (marginally but measurably). In theory, this is a breaking change, as users will no longer be able to add arbitrary attributes to the `Assignment` and `SubgraphView` class. However, I don't think this is something that people do (it would be quite strange, no?).
This PR inspired by @pjrule #363. See that PR for more details on the reasoning.
> More __slots__

- gerrychain/partition/partition.py
- tests/partition/test_partition.py
This is a PR broken out from #372 to ease the code review process.
As noted in #368, the `cut_edges` updater is forcibly enabled by default for every Partition object. However, the user has no way of opting out of this expensive updater. Prior to `pcompress`, this wasn't a big deal. However, now that GerryChain runs are replayable (and since most analysis is now done with replayable chains), it doesn't make sense to force every partition to calculate the `cut_edges` updater. 
As an example case where this would be useful, let's say that we want to draw election histograms or simply export a few sample maps in a recorded chain run (a fairly common occurrence). In this case, there would be no need to calculate the `cut_edges` and disabling the updater by providing the `use_cut_edges` flag …
> Add option to disable cut_edges updater with use_cut_edges flag

- gerrychain/constraints/contiguity.py
- gerrychain/grid.py
- gerrychain/metagraph.py
- gerrychain/partition/partition.py
- gerrychain/proposals/proposals.py
- gerrychain/proposals/spectral_proposals.py
- gerrychain/proposals/tree_proposals.py
- gerrychain/updaters/compactness.py
- gerrychain/updaters/county_splits.py
- gerrychain/updaters/cut_edges.py
- gerrychain/updaters/flows.py
- gerrychain/updaters/locality_split_scores.py
This is a PR broken out from #372 to ease the code review process. These sets of PRs are the second and final batch -- after every PR from this batch is merged in, the entire `perf-tuning` branch will be considered fully merged in and done.
> Replace references to assignment[node] to assignment.mapping[node] to reduce __getitem__ overhead

- gerrychain/partition/assignment.py
- gerrychain/partition/partition.py
- tests/constraints/test_validity.py
- tests/partition/test_assignment.py
This is a PR broken out from #372 to ease the code review process -- this is the second batch of PRs, after which that `perf-tuning` branch will be considered fully merged in.
> Refactor out Assignment.update (replace with Assignment.update_flows) to prevent double-calculating flows

- gerrychain/partition/partition.py
- gerrychain/updaters/flows.py
- gerrychain/updaters/tally.py
This is a PR broken out from #372 to ease the code review process. These sets of PRs are the second and final batch -- after every PR from this batch is merged in, the entire `perf-tuning` branch will be considered fully merged in and done.
> Cache flow_from_changes

- gerrychain/tree.py
This patch adds a max_attempts argument to the bipartition_tree funcs in `gerrychain.tree`. If `max_attempts` is None, it will default to the previous behavior (i.e. it will hang if it gets stuck). If `max_attempts` is set, it will throw a RuntimeError when `max_attempts` is reached.
This patch is based off code from Robi Huq (via Jeanne Clelland), but is rewritten (to maintain backwards compatibility).
Any mistakes are likely my own.
> Add optional max_attempts argument to bipartition tree funcs

- gerrychain/graph/graph.py
I think this was accidentally introduced during one of my rebases -- oops!
> Remove duplicate frozen call in FrozenGraph

- gerrychain/partition/partition.py
- tests/partition/test_partition.py
Several GerryChain users have been reporting a bug in the most recent version of GerryChain where the default updaters in a `GeographicPartition` (e.g. `area`, `boundary_nodes`, etc.) are not being instantiated properly. This PR fixes the bug and adds regression tests to ensure that this doesn't happen again.
It also renames the `use_cut_edges` flag to `use_default_updaters`, which more accurately reflects its intended purpose.
> Fix default updaters bug in GeographicPartition

- tests/partition/test_partition.py
`mypy` detected a duplicate function definition, which this PR fixes by renaming the duplicate test name.
> Fix duplicate test name for geographic partition default updaters

- docs/api.rst
- gerrychain/meta/__init__.py
- gerrychain/meta/diversity.py
- tests/meta/test_diversity.py
This is a draft PR which adds a `collect_diversity_stats()` function that reports the diversity of a given chain. I will come back and add docs/tests.
> Implement diversity stats collector (collect_diversity_stats func)

- .circleci/config.yml
- gerrychain/graph/adjacency.py
- gerrychain/graph/graph.py
- setup.py
Shapely 2.0 will introduce breaking changes for GerryChain. In particular, our adjacency calculation code will break (and we won't be able to make new dual graphs). Although Shapely 2.0 hasn't stabilized yet, it appears that recent updates in our dependencies (i.e. geopandas) has caused some issues to show up prior to Shapely 2.0 being offically stable.
Relevant issues:
- Fixes #392
- Closes #287
#369 was originally a stop-gap fix for this PR. We should be able to remove the import warning in `gerrychain/__init__.py`.
> Port GerryChain adjacency calcs to Shapely 2.0

- gerrychain/tree.py
- tests/test_tree.py
See https://github.com/mggg/GerryChain/issues/414 for description of issue.
The solution is self-explanatory.
> #414 Use method in recursive calls to recursive_seed_part_inner

- gerrychain/chain.py
- gerrychain/tree.py
The edit to `chain.py` ensures that if a user only inputs one constraint to a `MarkovChain`, it will still be able to print the correct error message should the chain fail. The error message relies on the constraints being turned into a `Validator` object, and previously if the user input a single constraint it did not get turned into a `Validator`.
The edit to `tree.py` fixes an issue that occasionally caused `recursive_tree_part` to generate plans that were imbalanced in population. Here is an example to show why the previous computation was incorrect. Suppose the ideal size is 100, epsilon = .02, and the previous district had size 99. Then the debt=-1, the min_pop=99, and max_pop=102. The pop_target = 100.5, and the new value for epsilon is .015. But then the lower end of the …
> `MarkovChain` validators and `recursive_tree_part`
