mggg/GerryChain

- CONTRIBUTING.md
This is a rough draft of a contributors guideline. Hopefully it'll be useful to us and new people hopping on.
> Add a basic contributor guideline

- make_graph.py
Creates the graph object we will be running chain on.  Also includes a way to add data to the nodes of the graph so you can run different objective functions.
> Initial commit for underlying graph structure

- docs/conf.py
- docs/index.rst
- docs/models.rst
These commits are fairly minor changes to the doc configuration and structure to accommodate autodoc.
> Update docs for autodoc

- rundmcmc/ingest.py
- rundmcmc/make_graph.py
There are no functional changes here.
> Improve docstrings and style

- rundmcmc/__main__.py
- rundmcmc/partition.py
- rundmcmc/updaters.py
- rundmcmc/validity.py
- tests/test_partition.py
- tests/test_updaters.py
Suggestions for another word for "updater" are welcome!
> Can now inject updater functions to update Partition properties

- .circleci/config.yml
- conda.recipe/meta.yaml
> try to cache packages for circle ci

- rundmcmc/ingest.py
- rundmcmc/make_graph.py
Still needs some work-outline for the format for adjacencymatrix csv, adding excel option, etc. 
This also includes a change where the added node data can be optionally keyed on GEOID in case there is an ordering issue that needs to be resolved.
> allow csv adjacencymatrix instead of makefile

- rundmcmc/__main__.py
- rundmcmc/make_graph.py
- rundmcmc/partition.py
- rundmcmc/validity.py
very first implementation of graph-tool without optimizing to the api
> ROUGH port to graph-tool

- README.rst
- conda.recipe/meta.yaml
This adds a nicer intro for users and fixes the conda config to account for our weirdly placed test files.
This also adds a `v0.1.0` tag to indicate our first "release." There's still a lot of cleaning to do, but enough people are running the code that we should make it easier to access.
> Edit docs and improve conda build config

- README.rst
- rundmcmc/__main__.py
- rundmcmc/chain.py
- rundmcmc/defaults.py
- rundmcmc/grid.py
- rundmcmc/scores.py
- rundmcmc/updaters.py
- rundmcmc/validity.py
- tests/test_grid.py
- tests/test_validity.py
- Added BasicChain class to hold the default configuration we'll need to replicate the PA analysis. Right now it comes with validators for contiguity, population within 1%, and no-vanishing districts, along with cut_edges and population updaters.
- Changed the main script to use BasicChain, to reduce the amount of importing and configuration.
- Also fixed the error I introduced into main.
I also had to remove Efficiency Gap from the main script, because I found some problems with it - I implemented the wrong version of the formula again. So I'll need to work on that.
> Add BasicChain (MarkovChain some default updaters) class, and wrote test for population validator

- README.rst
- rundmcmc/defaults.py
- rundmcmc/scores.py
- rundmcmc/validity.py
- tests/test_grid.py
- tests/test_scores.py
- New efficiency gap implementation (thanks to @mjharris95), closing #83 
- Wrote tests for efficiency gap using examples from Moon's slides (lol)
- Polsby Popper validator for PA analysis runs
- Wrote up the ipython session demo we did this morning into README.rst
> Polsby popper validator, new efficiency gap, and ipython usage example

- rundmcmc/proposals.py
This speeds things up bc it removes an unecessary call to cut_edges.
> removed uneccesary cut_edges call

- rundmcmc/chain.py
- rundmcmc/defaults.py
- rundmcmc/proposals.py
- rundmcmc/scores.py
- rundmcmc/validity.py
- tests/test_updaters.py
- @caramnix and I wrote a Duke Gerrymandering Index implementation. This closes #84 .
- I added an alternative version of the 'population within one percent' constraint based on the language in Moon's PA report. I put that in defaults.py because it seemed to be giving different answers than `districts_within_tolerance`, but we can figure that out later.
We're almost ready to run the PA analysis!
> Duke Gerrymandering Index

- rundmcmc/__main__.py
- rundmcmc/defaults.py
- rundmcmc/proposals.py
- rundmcmc/run.py
- rundmcmc/scores.py
- rundmcmc/validity.py
The __main__ script now outputs some nice histograms. Woo!
> Main script for PA runs

- rundmcmc/chain.py
This way it counts self-loops as steps so that it only takes total_steps steps
> added counter incremement in self-loop case

- rundmcmc/proposals.py
I added comments to the proposals functions we wrote yesterday.
> Add comments to proposals.py

- rundmcmc/__main__.py
- rundmcmc/basic_config.ini
- rundmcmc/generate_config.py
- rundmcmc/make_graph.py
- rundmcmc/output.py
- rundmcmc/parse_config.py
- rundmcmc/run.py
- rundmcmc/updaters.py
CHANGES:
- Added config file parser so that main does not have to change for every run
- Changed get_list_of_data in make_graph to return a dataframe rather than a list of tuples
NOTES:
- basic config file sets up and runs PA for 1000 steps with histogram output per previous commit
- config parser file is MESSY. TODO: clean, standardize
- GUI for config file generating will be added soon to simplify runs
TODO: 
-  add the functions that visualize output to run.py (and make more. e.g. plots as well as hists)
-  add dependency list for updaters based on the validity/score functions that are selected
> Config file format added

- readthedocs.yaml
- readthedocs.yml
Here's looking at you, @maxhully.
> Add Python 3.6 to RTD

- rundmcmc/updaters.py
- rundmcmc/validity.py
The functions added parallel the continuous polsby-popper functions.  These have not been added to the defaults.py script.
> Add discrete polsby-popper updater

- rundmcmc/defaults.py
I know that the eventual plan is to hold no data in the repository, but for now it's very annoying to go fix paths when running files outside of the repository itself.
> Add absolute paths to test data

- examples/chain_multiprocessing.py
This is a first try at implementing multiprocessing for a "star-run" chain.
I'm not 100% sure that I got the p-value reporting correct, so maybe be careful about that part.
@maxhully
> Add first attempt to multiprocess a star-run

- rundmcmc/__main__.py
- rundmcmc/updaters/__init__.py
- setup.py
Also fixes the `rundmcmc PA.ini` routine.
> makes 'python setup.py install' install the rundmcmc.updaters package as well

- rundmcmc/accept.py
- rundmcmc/proposals.py
- rundmcmc/run.py
- rundmcmc/template_main.py
- rundmcmc/vis_output.py
Added 2 simple accept functions and 1 metagraph proposal. 
Changed the histogram plot to take number of bins as input and changed pipe_to_table to have separate bin vs. plot intervals. 
Failed test is due to the random import in proposals.py.
> Added simple accepts and un-hardcoded plots

- rundmcmc/run.py
changed default to make fuller histograms
> Bin everything now

- rundmcmc/validity.py
This does two things: Add docs to every possible function in `validity.py`, and order functions in a more cohesive way. (By "cohesive," I really just mean that classes come first and a few helper functions are now inline/hidden by underscores.)
> Overhaul validator style and docs

- rundmcmc/defaults.py
- rundmcmc/make_graph.py
- rundmcmc/template_main_multi.py
- tests/test_updaters.py
- `get_list_of_data` can now read any fiona-supported file (was anyone using this anyway?)
- Close #181
- `get_assignment_dict` now comes in two flavors: `_from_df` and `from_graph`
- Docstrings everywhere!
> Cleanup make_graph.py

- rundmcmc/make_graph.py
This rewrites `add_boundary_perimeters` to use dataframe operations instead of for-loops. Testing shows a sizable improvement.
A quick test on SC data (full results available if needed) gave:
- Pre change: 117.874 seconds
- Post change: 87.631 seconds
It shaved about 30 seconds off of the time to add perimeters, or about 38% of the runtime. Adding perimeters is still the longest operation, but should now be better.
> Rewrite boundary functions with dataframe operations

- rundmcmc/make_graph.py
Now all nodes should have the `boundary_node` boolean attribute. Sorry for the confusion, @drdeford!
> Fix add_boundary_perimeters to touch all nodes

- examples/four_histograms.py
- examples/p_value_reports.py
- rundmcmc/gui/__init__.py
- rundmcmc/gui/parse_config.py
- rundmcmc/gui/run.py
- rundmcmc/output/__init__.py
- rundmcmc/output/output.py
- rundmcmc/templates/template_main.py
- rundmcmc/templates/template_main_multi.py
This moves some things that seem more like output features into the output folder.
> Move parts of /run into /output

- rundmcmc/scores.py
Adding some of the basic chain report values to scores.py
> Some simple chain status scores

- rundmcmc/gui/parse_config.py
- rundmcmc/make_graph.py
- rundmcmc/templates/template_main.py
- rundmcmc/validity/validity.py
- tests/test_make_graph.py
relevant function is: 
- proposed_changes_still_contiguous()
in validity/validity.py
> validity check for only the districts involved in partition.flips added

- rundmcmc/make_graph.py
This also changes the `geo_data_frame` data source type to `geodataframe`, which is more consistent with the actual name. (Though maybe it should be `GeoDataFrame`.)
> Add warning messages to make_graph.py

- rundmcmc/make_graph.py
This now uses the canonical `df.geometry` series that GeoDataFrames have. To do
this in add_boundary_perimeters(), I also rewrote things to be more dataframe
friendly.
> Remove references to "geometry" column

- rundmcmc/proposals.py
Adds a proposals that flips a random node to a random part.
Reversible but not sensible.
> noncontiguous flip

- rundmcmc/validity/__init__.py
- rundmcmc/validity/validity.py
Added new, non-reciprocal PP scores for MA. Also updated init to expose more validity functions
> L1 and L2 PP score, updated init

- rundmcmc/accept.py
- rundmcmc/make_graph.py
- rundmcmc/templates/template_main_grid.py
Some shapefiles were giving populations, votes, etc. as strings. Now make_graph coerces those to be numeric on the dataframe.
> Forces columns on dataframes to be numbers

- rundmcmc/accept.py
- rundmcmc/entropiesReport.py
- rundmcmc/initial_report.py
- rundmcmc/make_graph.py
- rundmcmc/scores.py
Initial report updates to be more flexible and less numerically indexed.
> Inital report updates and small MH fixes

- .circleci/config.yml
- rundmcmc/make_graph.py
- setup.py
This does add a dependency (`utm`), which is not ideal.
Something not included in this PR: always computing areas ourselves, rather than accepting an area column. This might be wise in the future so that we are sure about which projection was used.
> Compute area and perimeter in a UTM projection

- docs/api.rst
- gerrychain/graph/adjacency.py
- gerrychain/graph/graph.py
- gerrychain/updaters/election.py
The `Graph.from_file` signature doesn't match the Getting started guide, so I'm bringing it into line.
Also adding documentation for the Election updater class.
> Add Election documentation, fix `Graph.from_file` API

- gerrychain/tree_methods.py
- gerrychain/tree_proposals.py
First draft at getting the tree proposals and related functions
> Tree Methods for GerryChain

- docs/conf.py
- docs/user/quickstart.rst
- gerrychain/chain.py
- gerrychain/constraints/__init__.py
- gerrychain/constraints/bounds.py
- setup.py
- Reset the MarkovChain to initial state before iterating.
- Switch to RTD docs theme
- Add WithinPercentRangeOfBounds back in
> Revise documentation, add matplotlib requirement, & more

- gerrychain/partition/partition.py
- tests/test_partition.py
- tests/test_reproducibility.py
I'm activating and updating the reproducibility test to make sure that it works. I expect that we'll have to turn it off again the next time we change something, but I wanted to check up on it before releasing the next version.
> Update reproducibility test

- README.rst
- gerrychain/constraints/bounds.py
- gerrychain/constraints/contiguity.py
- gerrychain/constraints/validity.py
- gerrychain/graph/graph.py
- gerrychain/partition/subgraphs.py
- gerrychain/proposals/proposals.py
- tests/test_bounds.py
- tests/test_contiguity.py
- tests/test_proposals.py
Just adding some more tests and minor changes before making another PyPI release.
> Tighten screws before release

- gerrychain/tree.py
- tests/test_tree.py
This PR adjusts the bipartition_tree function to be non-recursive, closing #276 and hopefully fixing the recursion depth errors people have been having.
> Non-recursive bipartition_tree

- gerrychain/proposals/proposals.py
- tests/test_proposals.py
Actual uniformity without needing to normalize with an accept function. The previous version has been renamed and only works for bipartitions, naively.
> More uniformity

- gerrychain/graph/graph.py
- tests/test_make_graph.py
> Reproject=false

- gerrychain/tree.py
- tests/test_tree.py
The `recursive_tree_part()` function attempts to partition a population-labeled labeled graph with _n_ people into _m_ subgraphs (districts) with some population tolerance ϵ. The target population for each subgraph is _T = n/m_.  Over many runs, I've observed a consistent behavior where the first _m-1_ subgraphs all end up with populations below the target; accordingly, the _m_-th subgraph wildly overshoots the target population. It is also possible for the reverse effect to occur, where the _m_-th subgraph _undershoots_ the target population. These issues occur because the current version of the function makes no attempt to keep track of accumulated error (see issue #312). The maximum error is ± (_m-1_)ϵ—that is, maximum error is linear with the number of districts—so this issue is …
> Add population debt to recursive_tree_part()

- gerrychain/tree.py
Added sampling from a uniform spanning tree distribution. This code is merely a piece extraction from @pjrule 's PR #339 .
> Add Uniform Spanning Tree functionality, via @pjrule

- gerrychain/proposals/tree_proposals.py
- gerrychain/tree.py
- tests/test_tree.py
New algorithm that finds the balanced cut edge, via @pjrule 's #339
> add memoization balance edge algorithm

- gerrychain/tree.py
See changes for explanation! Hopefully they are self-explanatory
> change weight key to be called random_weight

- gerrychain/proposals/tree_proposals.py
- gerrychain/tree.py
- setup.cfg
We've discovered a minor issue with how probabilities are computed in the last rejection step of our reversible ReCom implementation. This PR brings the code in sync with our current draft of the paper.
> Fix reversible ReCom

- gerrychain/partition/assignment.py
This is a PR broken out from #372 to ease the code review process. These sets of PRs are the second and final batch -- after every PR from this batch is merged in, the entire `perf-tuning` branch will be considered fully merged in and done.
> Simplify Assignment iterators

- gerrychain/graph/graph.py
- gerrychain/grid.py
- gerrychain/partition/partition.py
- gerrychain/proposals/spectral_proposals.py
- gerrychain/proposals/tree_proposals.py
- gerrychain/tree.py
- gerrychain/updaters/county_splits.py
- gerrychain/updaters/tally.py
- setup.py
- tests/conftest.py
- tests/constraints/test_validity.py
- tests/partition/test_partition.py
- tests/test_reproducibility.py
- tests/test_tree.py
- tests/updaters/test_updaters.py
This is a PR broken out from #372 to ease the code review process. These sets of PRs are the second and final batch -- after every PR from this batch is merged in, the entire `perf-tuning` branch will be considered fully merged in and done.
> Frozen graph implementation!

- .circleci/config.yml
- README.rst
- docs/user/install.rst
- gerrychain/__init__.py
- gerrychain/graph/adjacency.py
- gerrychain/graph/geo.py
- gerrychain/graph/graph.py
- gerrychain/partition/partition.py
- setup.py
This allows us to explore things like packaging GerryChain for the browser via Pyodide.
> Make geospatial packages an optional dependency

- gerrychain/tree.py
> Use node_repeats in _bipartitions_tree_random_all

- gerrychain/updaters/election.py
if two parties tie for first place, the current code will count both of them as winners. this code changes the logic so that a party is a winner if and only if it has more votes than all other opponents.
> ties are not wins
